# Generated by Django 4.2.10 on 2024-05-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
