# Generated by Django 4.2.10 on 2024-05-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_hub', '0002_alter_notice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='articles/default.jpg', null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
