# Generated by Django 4.2.13 on 2024-06-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkm', '0002_initial'),
        ('proposals', '0002_initial'),
        ('content_hub', '0003_article_content_type_article_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='object_id',
        ),
        migrations.AddField(
            model_name='article',
            name='idea_contribute',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'P'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='pkm.pkmideacontribute'),
        ),
        migrations.AddField(
            model_name='article',
            name='submission_proposal_apply',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': ['PASSED', 'PASSED FUNDING']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.submissionsproposalapply'),
        ),
    ]
