# Generated by Django 4.2.10 on 2024-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_hub', '0003_article_excerpt_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, null=True, verbose_name='kutipan'),
        ),
    ]
