# Generated by Django 4.2.13 on 2024-06-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_initial'),
        ('content_hub', '0004_remove_article_content_type_remove_article_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='submission_proposal_apply',
            field=models.ForeignKey(blank=True, limit_choices_to={'status__in': ['PASSED', 'PASSED FUNDING']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.submissionsproposalapply'),
        ),
    ]
