# Generated by Django 4.2.13 on 2024-10-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_hub', '0005_alter_article_submission_proposal_apply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created'], 'verbose_name': 'Penguumuman', 'verbose_name_plural': 'Pengumuman'},
        ),
    ]
