version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e_research
    restart: always
    networks:
      - e-research
    # Uncomment and use the ports and volumes as needed
    # ports:
    #   - "8000:8000"
    # volumes:
    #   - .:/app

networks:
  e-research:
    driver: bridge