# Generated by Django 4.2.10 on 2024-05-23 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PKMScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Schema PKM',
                'verbose_name_plural': 'Schema PKM',
            },
        ),
        migrations.CreateModel(
            name='PKMProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('period', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('scheme', models.ManyToManyField(related_name='programs', to='pkm.pkmscheme')),
            ],
            options={
                'verbose_name': 'Program PKM',
                'verbose_name_plural': 'Program PKM',
            },
        ),
        migrations.CreateModel(
            name='PKMActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_schedules', to='pkm.pkmprogram')),
            ],
            options={
                'verbose_name': 'Jadwal Kegiatan PKM',
                'verbose_name_plural': 'Jadwal Kegiatan PKM',
            },
        ),
    ]
