# Generated by Django 4.2.13 on 2024-06-21 13:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PKMActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Jadwal Kegiatan PKM',
                'verbose_name_plural': 'Jadwal Kegiatan PKM',
            },
        ),
        migrations.CreateModel(
            name='PKMIdeaContribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('solution', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pkm/idea_contribute/')),
                ('document', models.FileField(blank=True, null=True, upload_to='pkm/idea_contribute/')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('A', 'Archived'), ('R', 'Rejected')], default='D', max_length=1)),
                ('applied_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bank Judul',
                'verbose_name_plural': 'Bank Judul',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PKMScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Schema PKM',
                'verbose_name_plural': 'Schema PKM',
            },
        ),
        migrations.CreateModel(
            name='PKMProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('scheme', models.ManyToManyField(related_name='programs', to='pkm.pkmscheme')),
            ],
            options={
                'verbose_name': 'Program PKM',
                'verbose_name_plural': 'Program PKM',
            },
        ),
        migrations.CreateModel(
            name='PKMIdeaContributeApplyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('idea_contribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_teams', to='pkm.pkmideacontribute')),
            ],
            options={
                'verbose_name': 'Apply Team Idea Contribute',
                'verbose_name_plural': 'Apply Team Idea Contribute',
            },
        ),
    ]
