# Generated by Django 4.2.10 on 2024-05-25 05:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('pkm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PKMIdeaContribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='pkm/idea_contribute/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pkm/idea_contribute/')),
                ('document', models.FileField(blank=True, null=True, upload_to='pkm/idea_contribute/')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('A', 'Archived'), ('R', 'Rejected')], default='D', max_length=1)),
                ('applied_date', models.DateTimeField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Idea Contribute',
                'verbose_name_plural': 'Idea Contribute',
            },
        ),
    ]
