# Generated by Django 4.2.10 on 2024-06-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkm', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkmprogram',
            name='name',
        ),
    ]
