# Generated by Django 4.2.10 on 2024-05-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_teamvacanicies_teamvacancies'),
        ('pkm', '0003_pkmideacontribute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkmideacontribute',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_contribute', to='team.team'),
        ),
    ]
