# Generated by Django 4.2.10 on 2024-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm', '0003_remove_pkmprogram_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pkmideacontribute',
            options={'ordering': ['-created'], 'verbose_name': 'Bank Judul', 'verbose_name_plural': 'Bank Judul'},
        ),
        migrations.AlterField(
            model_name='pkmideacontribute',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
