# Generated by Django 4.2.10 on 2024-06-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm', '0004_alter_pkmideacontribute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmideacontribute',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
