# Generated by Django 4.2.10 on 2024-05-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm', '0004_pkmideacontribute_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmideacontribute',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
