# Generated by Django 4.2.10 on 2024-05-30 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm', '0006_alter_pkmideacontribute_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmideacontribute',
            name='problem',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='pkmideacontribute',
            name='solution',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
