# Generated by Django 4.2.10 on 2024-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm', '0007_alter_pkmideacontribute_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkmideacontribute',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='pkmideacontribute',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
