# Generated by Django 4.2.10 on 2024-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm', '0012_pkmideacontributeapplyteam_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkmideacontributeapplyteam',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
