# Generated by Django 4.2.10 on 2024-05-23 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utils.handle_file_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
        ('account', '0002_remove_user_otp_user_string_activation'),
        ('pkm', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStageAssesment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Parameter Penilaian Tahap 1',
                'verbose_name_plural': 'Parameter Penilaian Tahap 1',
            },
        ),
        migrations.CreateModel(
            name='KeyStageAssesment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('presentase', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ManyToManyField(related_name='key_assesments', to='pkm.pkmscheme')),
            ],
            options={
                'verbose_name': 'Parameter Penilaian Tahap 2',
                'verbose_name_plural': 'Parameter Penilaian Tahap 2',
            },
        ),
        migrations.CreateModel(
            name='SubmissionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_time', models.DateTimeField()),
                ('addional_file', models.FileField(blank=True, null=True, upload_to=utils.handle_file_upload.UploadToPathAndRename('proposals\\submission_proposal/file'))),
                ('status', models.CharField(choices=[('ARCHIVED', 'Archived'), ('PUBLISHED', 'Published')], default='SUBMITTED', max_length=10)),
                ('program', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pkm.pkmprogram')),
            ],
            options={
                'verbose_name_plural': '1. Submission Proposal',
            },
        ),
        migrations.CreateModel(
            name='SubmissionsProposalApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PASSED FUNDING', 'Passed Funding')], default='APPLIED', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions_proposals_apply', to='pkm.pkmscheme')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions_proposals_apply', to='account.lecturer')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='proposals.submissionproposal')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_proposals_apply', to='team.team')),
            ],
            options={
                'verbose_name_plural': '2. Pengumpulan Proposal',
                'unique_together': {('team', 'submission')},
            },
        ),
        migrations.CreateModel(
            name='ProposalIdeaContribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to=utils.handle_file_upload.UploadToPathAndRename('proposals\\proposal_idea_contribute/illustration'))),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.handle_file_upload.UploadToPathAndRename('proposals\\proposal_idea_contribute/file'))),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='team.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '4. Ide Usulan Proposal',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.handle_file_upload.UploadToPathAndRename('proposals\\proposal/file'))),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='team.team')),
            ],
            options={
                'verbose_name_plural': '5. Proposal Mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='LecturerTeamSubmissionApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_submission_apply', to='account.lecturer')),
                ('submission_apply', models.ManyToManyField(related_name='lecturers', to='proposals.submissionsproposalapply')),
            ],
            options={
                'verbose_name': 'Plot Team Mahasiswa - Reviewer',
                'verbose_name_plural': 'Plot Team Mahasiswa - Reviewer',
            },
        ),
        migrations.CreateModel(
            name='AssesmentSubmissionsProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('STAGE1', 'Stage 1'), ('STAGE2', 'Stage 2'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision')], default='IDLE', max_length=10)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='account.lecturer')),
                ('submission_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='proposals.submissionsproposalapply')),
            ],
            options={
                'verbose_name_plural': '3.Penilaian Proposal',
                'unique_together': {('submission_apply', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='StageAssesment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_2', to='proposals.assesmentsubmissionsproposal')),
                ('key_assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_2', to='proposals.keystageassesment2')),
            ],
            options={
                'verbose_name': 'Penilaian Tahap 2',
                'verbose_name_plural': 'Penilaian Tahap 2',
                'unique_together': {('key_assesment', 'assesment')},
            },
        ),
        migrations.CreateModel(
            name='StageAssesment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_1', to='proposals.assesmentsubmissionsproposal')),
                ('key_assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_1', to='proposals.keystageassesment1')),
            ],
            options={
                'verbose_name': 'Penilaian Tahap 1',
                'verbose_name_plural': 'Penilaian Tahap 1',
                'unique_together': {('key_assesment', 'assesment')},
            },
        ),
    ]
