# Generated by Django 4.2.13 on 2024-06-21 13:26

from django.db import migrations, models
import django.db.models.deletion
import utils.handle_file_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pkm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssesmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('revision', models.CharField(choices=[('Revision Minor', 'Revision Minor'), ('Revision Major', 'Revision Major'), ('No Revision', 'No Revision')], default='No Revision', max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Penilaian',
                'verbose_name_plural': 'Review Penilaian',
            },
        ),
        migrations.CreateModel(
            name='AssesmentSubmissionsProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Penilaian Proposal',
            },
        ),
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laporan Penilaian',
                'verbose_name_plural': 'Laporan Penilaian',
            },
        ),
        migrations.CreateModel(
            name='KeyStageAssesment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Parameter Penilaian Tahap 1',
                'verbose_name_plural': 'Parameter Penilaian Tahap 1',
            },
        ),
        migrations.CreateModel(
            name='KeyStageAssesment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('presentase', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bobot')),
            ],
            options={
                'verbose_name': 'Parameter Penilaian Tahap 2',
                'verbose_name_plural': 'Parameter Penilaian Tahap 2',
            },
        ),
        migrations.CreateModel(
            name='LecturerTeamSubmissionApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Pembagian Team & Reviewer',
            },
        ),
        migrations.CreateModel(
            name='StageAssesment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Penilaian Tahap 1',
                'verbose_name_plural': 'Penilaian Tahap 1',
            },
        ),
        migrations.CreateModel(
            name='StageAssesment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (5, '5'), (6, '6'), (7, '7')])),
            ],
            options={
                'verbose_name': 'Penilaian Tahap 2',
                'verbose_name_plural': 'Penilaian Tahap 2',
            },
        ),
        migrations.CreateModel(
            name='SubmissionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('BATCH 1', 'Batch 1'), ('BATCH 2', 'Batch 2'), ('BATCH 3', 'Batch 3'), ('REVISION', 'Revision')], default='BATCH 1', max_length=10, verbose_name='Batch')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_time', models.DateTimeField()),
                ('additional_file', models.FileField(blank=True, null=True, upload_to=utils.handle_file_upload.UploadToPathAndRename('proposals\\submission_proposal/additional_file'))),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('ARCHIVED', 'Archived'), ('PUBLISHED', 'Published')], default='SUBMITTED', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Submission Proposals',
            },
        ),
        migrations.CreateModel(
            name='SubmissionsProposalApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision'), ('PASSED', 'Passed'), ('PASSED FUNDING', 'Passed Funding')], default='APPLIED', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('proposal', models.FileField(upload_to=utils.handle_file_upload.UploadToPathAndRename('proposals\\submission_proposal/apply'))),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions_proposals_apply', to='pkm.pkmscheme')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='proposals.submissionproposal')),
            ],
            options={
                'verbose_name_plural': 'Proposal Mahasiswa',
            },
        ),
    ]
