# Generated by Django 4.2.10 on 2024-06-12 05:03

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utils.handle_file_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('pkm', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssesmentSubmissionsProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Penilaian Proposal',
            },
        ),
        migrations.CreateModel(
            name='KeyStageAssesment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Parameter Penilaian Tahap 1',
                'verbose_name_plural': 'Parameter Penilaian Tahap 1',
            },
        ),
        migrations.CreateModel(
            name='KeyStageAssesment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('presentase', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Parameter Penilaian Tahap 2',
                'verbose_name_plural': 'Parameter Penilaian Tahap 2',
            },
        ),
        migrations.CreateModel(
            name='LecturerTeamSubmissionApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '3. Plot Team Mahasiswa - Reviewer',
                'verbose_name_plural': '3. Plot Team Mahasiswa - Reviewer',
            },
        ),
        migrations.CreateModel(
            name='StageAssesment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Penilaian Tahap 1',
                'verbose_name_plural': 'Penilaian Tahap 1',
            },
        ),
        migrations.CreateModel(
            name='StageAssesment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
            ],
            options={
                'verbose_name': 'Penilaian Tahap 2',
                'verbose_name_plural': 'Penilaian Tahap 2',
            },
        ),
        migrations.CreateModel(
            name='SubmissionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_time', models.DateTimeField()),
                ('addional_file', models.FileField(blank=True, null=True, upload_to=utils.handle_file_upload.UploadToPathAndRename('proposals\\submission_proposal/file'))),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('ARCHIVED', 'Archived'), ('PUBLISHED', 'Published')], default='SUBMITTED', max_length=10)),
            ],
            options={
                'verbose_name_plural': '1. Submission Proposal',
            },
        ),
        migrations.CreateModel(
            name='SubmissionsProposalApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision'), ('PASSED', 'Passed'), ('PASSED FUNDING', 'Passed Funding')], default='APPLIED', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('proposal', models.FileField(upload_to=utils.handle_file_upload.UploadToPathAndRename('proposals\\submission_proposal/apply'))),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions_proposals_apply', to='pkm.pkmscheme')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions_proposals_apply', to='account.lecturer')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='proposals.submissionproposal')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': '2. Pengumpulan Proposal',
            },
        ),
    ]
