# Generated by Django 4.2.10 on 2024-06-12 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        ('account', '0001_initial'),
        ('pkm', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionsproposalapply',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_proposals_apply', to='team.team'),
        ),
        migrations.AddField(
            model_name='submissionproposal',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pkm.pkmprogram'),
        ),
        migrations.AddField(
            model_name='stageassesment2',
            name='assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_2', to='proposals.assesmentsubmissionsproposal'),
        ),
        migrations.AddField(
            model_name='stageassesment2',
            name='key_assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_2', to='proposals.keystageassesment2'),
        ),
        migrations.AddField(
            model_name='stageassesment1',
            name='assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_1', to='proposals.assesmentsubmissionsproposal'),
        ),
        migrations.AddField(
            model_name='stageassesment1',
            name='key_assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_1', to='proposals.keystageassesment1'),
        ),
        migrations.AddField(
            model_name='lecturerteamsubmissionapply',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_submission_apply', to='account.lecturer'),
        ),
        migrations.AddField(
            model_name='lecturerteamsubmissionapply',
            name='submission_apply',
            field=models.ManyToManyField(related_name='lecturers', to='proposals.submissionsproposalapply'),
        ),
        migrations.AddField(
            model_name='keystageassesment2',
            name='category',
            field=models.ManyToManyField(related_name='key_assesments', to='pkm.pkmscheme'),
        ),
        migrations.AddField(
            model_name='assesmentsubmissionsproposal',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='account.lecturer'),
        ),
        migrations.AddField(
            model_name='assesmentsubmissionsproposal',
            name='submission_apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='proposals.submissionsproposalapply'),
        ),
        migrations.AlterUniqueTogether(
            name='stageassesment2',
            unique_together={('key_assesment', 'assesment')},
        ),
        migrations.AlterUniqueTogether(
            name='stageassesment1',
            unique_together={('key_assesment', 'assesment')},
        ),
        migrations.AlterUniqueTogether(
            name='assesmentsubmissionsproposal',
            unique_together={('submission_apply', 'reviewer')},
        ),
    ]
