# Generated by Django 4.2.13 on 2024-06-21 13:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pkm', '0002_initial'),
        ('account', '0001_initial'),
        ('taggit', '0001_initial'),
        ('proposals', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionsproposalapply',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='submissionsproposalapply',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_proposals_apply', to='team.team'),
        ),
        migrations.AddField(
            model_name='submissionproposal',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pkm.pkmprogram'),
        ),
        migrations.AddField(
            model_name='stageassesment2',
            name='assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_2', to='proposals.assesmentsubmissionsproposal'),
        ),
        migrations.AddField(
            model_name='stageassesment2',
            name='key_assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_2', to='proposals.keystageassesment2'),
        ),
        migrations.AddField(
            model_name='stageassesment1',
            name='assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_1', to='proposals.assesmentsubmissionsproposal'),
        ),
        migrations.AddField(
            model_name='stageassesment1',
            name='key_assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_1', to='proposals.keystageassesment1'),
        ),
        migrations.AddField(
            model_name='lecturerteamsubmissionapply',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_submission_apply', to='account.lecturer'),
        ),
        migrations.AddField(
            model_name='lecturerteamsubmissionapply',
            name='submission_apply',
            field=models.ManyToManyField(related_name='lecturers', to='proposals.submissionsproposalapply'),
        ),
        migrations.AddField(
            model_name='keystageassesment2',
            name='category',
            field=models.ManyToManyField(related_name='key_assesments', to='pkm.pkmscheme'),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='assessment_review',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_report', to='proposals.assesmentreview'),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='assessment_submission_proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_report', to='proposals.assesmentsubmissionsproposal'),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='stage_assessment_2',
            field=models.ManyToManyField(blank=True, related_name='assessment_report', to='proposals.stageassesment2'),
        ),
        migrations.AddField(
            model_name='assesmentsubmissionsproposal',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='account.lecturer'),
        ),
        migrations.AddField(
            model_name='assesmentsubmissionsproposal',
            name='submission_apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='proposals.submissionsproposalapply'),
        ),
        migrations.AddField(
            model_name='assesmentreview',
            name='assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesment_report', to='proposals.assesmentsubmissionsproposal'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionsproposalapply',
            unique_together={('team', 'submission')},
        ),
        migrations.AlterUniqueTogether(
            name='stageassesment2',
            unique_together={('key_assesment', 'assesment')},
        ),
        migrations.AlterUniqueTogether(
            name='stageassesment1',
            unique_together={('key_assesment', 'assesment')},
        ),
        migrations.AlterUniqueTogether(
            name='assesmentsubmissionsproposal',
            unique_together={('submission_apply', 'reviewer')},
        ),
    ]
