# Generated by Django 4.2.10 on 2024-06-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionproposal',
            name='title',
            field=models.CharField(choices=[('BATCH 1', 'Batch 1'), ('BATCH 2', 'Batch 2'), ('BATCH 3', 'Batch 3'), ('REVISION', 'Revision')], default='BATCH 1', max_length=10, verbose_name='Batch'),
        ),
    ]
