# Generated by Django 4.2.10 on 2024-06-12 05:58

from django.db import migrations, models
import utils.handle_file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_submissionproposal_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionproposal',
            name='addional_file',
        ),
        migrations.AddField(
            model_name='submissionproposal',
            name='additional_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.handle_file_upload.UploadToPathAndRename('proposals\\submission_proposal/additional_file')),
        ),
    ]
