# Generated by Django 4.2.10 on 2024-05-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_remove_assesmentsubmissionsproposal_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProposalIdeaContribute',
        ),
    ]
