# Generated by Django 4.2.10 on 2024-05-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_delete_proposalideacontribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assesmentsubmissionsproposal',
            options={'verbose_name_plural': 'Penilaian Proposal'},
        ),
        migrations.AlterModelOptions(
            name='lecturerteamsubmissionapply',
            options={'verbose_name': '3. Plot Team Mahasiswa - Reviewer', 'verbose_name_plural': '3. Plot Team Mahasiswa - Reviewer'},
        ),
    ]
