# Generated by Django 4.2.10 on 2024-06-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_remove_submissionproposal_addional_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stageassesment1',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stageassesment1',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stageassesment1',
            name='key_assesment',
        ),
        migrations.AddField(
            model_name='stageassesment1',
            name='key_assesment',
            field=models.ManyToManyField(related_name='assessment_values_1', to='proposals.keystageassesment1'),
        ),
    ]
