# Generated by Django 4.2.10 on 2024-06-12 07:25

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_alter_stageassesment1_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageassesment1',
            name='key_assesment',
        ),
        migrations.AddField(
            model_name='stageassesment1',
            name='key_assesment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_values_1', to='proposals.keystageassesment1'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stageassesment1',
            unique_together={('key_assesment', 'assesment')},
        ),
    ]