# Generated by Django 4.2.10 on 2024-05-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_alter_submissionsproposalapply_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionproposal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
