# Generated by Django 4.2.10 on 2024-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_alter_stageassesment1_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystageassesment1',
            name='title',
            field=models.CharField(),
        ),
    ]
