# Generated by Django 4.2.10 on 2024-05-31 13:51

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('proposals', '0007_submissionproposal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionsproposalapply',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='submissionsproposalapply',
            name='title',
            field=models.CharField(default='tes', max_length=200),
            preserve_default=False,
        ),
    ]
