# Generated by Django 4.2.10 on 2024-06-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_alter_keystageassesment1_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystageassesment1',
            name='title',
            field=models.TextField(max_length=180),
        ),
    ]
