# Generated by Django 4.2.10 on 2024-06-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_alter_keystageassesment1_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystageassesment2',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
