# Generated by Django 4.2.10 on 2024-06-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_alter_submissionsproposalapply_proposal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submissionsproposalapply',
            unique_together=set(),
        ),
    ]
