# Generated by Django 4.2.10 on 2024-06-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_alter_keystageassesment2_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageassesment1',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
