# Generated by Django 4.2.10 on 2024-06-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_stageassesment1_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageassesment2',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Catatan'),
        ),
        migrations.AddField(
            model_name='stageassesment2',
            name='revision',
            field=models.CharField(choices=[('Revision Minor', 'Revision Minor'), ('Revision Major', 'Revision Major'), ('No Revision', 'No Revision')], default='No Revision', max_length=20),
        ),
        migrations.AlterField(
            model_name='stageassesment2',
            name='score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (5, '5'), (6, '6'), (7, '7')]),
        ),
    ]
