# Generated by Django 4.2.10 on 2024-06-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_stageassesment2_comment_stageassesment2_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesmentsubmissionsproposal',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='stageassesment2',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='stageassesment2',
            name='revision',
        ),
        migrations.CreateModel(
            name='AssesmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='')),
                ('revision', models.CharField(choices=[('Revision Minor', 'Revision Minor'), ('Revision Major', 'Revision Major'), ('No Revision', 'No Revision')], default='No Revision', max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesment_report', to='proposals.assesmentsubmissionsproposal')),
            ],
            options={
                'verbose_name': 'Laporan Penilaian',
                'verbose_name_plural': 'Laporan Penilaian',
            },
        ),
    ]
