# Generated by Django 4.2.10 on 2024-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_assesmentreport_final_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesmentreport',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
