# Generated by Django 4.2.10 on 2024-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_alter_assesmentreport_final_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystageassesment2',
            name='presentase',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bobot'),
        ),
    ]
