# Generated by Django 4.2.10 on 2024-06-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_alter_keystageassesment2_presentase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssesmentReport',
            new_name='AssesmentReview',
        ),
        migrations.AlterModelOptions(
            name='assesmentreview',
            options={'verbose_name': 'Review Penilaian', 'verbose_name_plural': 'Review Penilaian'},
        ),
        migrations.AlterModelOptions(
            name='lecturerteamsubmissionapply',
            options={'verbose_name': 'Pembagian Team & Reviewer'},
        ),
        migrations.AlterModelOptions(
            name='submissionproposal',
            options={'verbose_name_plural': 'Submission Proposals'},
        ),
        migrations.AlterModelOptions(
            name='submissionsproposalapply',
            options={'verbose_name_plural': 'Proposal Mahasiswa'},
        ),
    ]
