# Generated by Django 4.2.10 on 2024-06-14 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_rename_assesmentreport_assesmentreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssesmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_details', models.TextField(blank=True, default='')),
                ('submission_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesment_reports', to='proposals.submissionsproposalapply')),
            ],
            options={
                'verbose_name': 'Laporan Penilaian',
                'verbose_name_plural': 'Laporan Penilaian',
            },
        ),
    ]
