# Generated by Django 4.2.10 on 2024-06-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('proposals', '0018_assessmentreport_delete_assesmentreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submissionsproposalapply',
            unique_together={('team', 'submission')},
        ),
        migrations.RemoveField(
            model_name='submissionsproposalapply',
            name='lecturer',
        ),
    ]
