# Generated by Django 4.2.10 on 2024-06-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_alter_submissionsproposalapply_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentreport',
            options={'verbose_name': 'Laporan Penilaian', 'verbose_name_plural': 'Laporan Penilaian'},
        ),
        migrations.RemoveField(
            model_name='assessmentreport',
            name='stage_assessment_1',
        ),
    ]
