# Generated by Django 4.2.10 on 2024-06-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_alter_assessmentreport_assessment_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentreport',
            name='stage_assessment_2',
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='stage_assessment_2',
            field=models.ManyToManyField(blank=True, related_name='assessment_report', to='proposals.stageassesment2'),
        ),
    ]
