# Generated by Django 4.2.10 on 2024-06-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_remove_assessmentreport_stage_assessment_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionsproposalapply',
            name='title',
            field=models.CharField(),
        ),
    ]
