# Generated by Django 4.2.10 on 2024-06-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0023_alter_submissionsproposalapply_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionsproposalapply',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
