# Generated by Django 4.2.10 on 2024-05-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='attachment',
        ),
    ]
