# Generated by Django 4.2.10 on 2024-06-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_alter_notification_options_notification_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('error', 'error'), ('success', 'success')], default='info', max_length=10),
        ),
    ]
