# Generated by Django 4.2.10 on 2024-06-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_remove_notification_id_notification_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='slug',
        ),
    ]
