# Generated by Django 4.2.10 on 2024-06-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_remove_notification_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['read', '-timestamp']},
        ),
    ]
