# Generated by Django 4.2.10 on 2024-05-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.AddField(
            model_name='user',
            name='string_activation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
