# Generated by Django 4.2.10 on 2024-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_departement_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Singkatan'),
        ),
    ]
