# Generated by Django 4.2.10 on 2024-05-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_otp_user_string_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
