# Generated by Django 4.2.10 on 2024-05-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='agency',
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
