# Generated by Django 4.2.10 on 2024-06-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_major_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='major',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
    ]
