# Generated by Django 4.2.10 on 2024-06-16 13:44

from django.db import migrations, models
import utils.handle_file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_departement_color_major_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.handle_file_upload.UploadToPathAndRename('profile\\images')),
        ),
    ]
