# Generated by Django 4.2.10 on 2024-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_userprofile_agency_user_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agency',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
