# Generated by Django 4.2.10 on 2024-05-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.userprofile')),
            ],
            bases=('account.userprofile',),
        ),
    ]
