# Generated by Django 4.2.10 on 2024-05-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agency',
        ),
        migrations.AddField(
            model_name='guest',
            name='agency',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
