# Generated by Django 4.2.10 on 2024-05-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamVacanicies',
            new_name='TeamVacancies',
        ),
    ]
