# Generated by Django 4.2.10 on 2024-05-31 22:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamvacancies',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='teamvacancies',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
