# Generated by Django 4.2.10 on 2024-06-01 13:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('team', '0004_teamvacancies_requirements_teamvacancies_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamvacancies',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
