# Generated by Django 4.2.10 on 2024-06-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teamvacancies_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
