# Generated by Django 4.2.10 on 2024-06-09 10:42

from django.db import migrations, models
import utils.handle_file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_remove_taggedwhatever_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='file_approvement_lecturer',
            field=models.FileField(default='default.pdf', upload_to=utils.handle_file_upload.UploadToPathAndRename('team/approvement/')),
            preserve_default=False,
        ),
    ]
