# Generated by Django 4.2.10 on 2024-06-10 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_alter_team_file_approvement_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtask',
            name='id',
        ),
        migrations.AddField(
            model_name='teamtask',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
