# Generated by Django 4.2.10 on 2024-06-11 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_agency_guest_agency'),
        ('team', '0011_remove_teamtask_id_teamtask_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='account.student'),
        ),
    ]
