name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Corrected to a valid runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Stop and remove previous Docker container
      run: |
        docker stop e-research-container || true
        docker rm e-research-container || true

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nurhavid1/e-research-server:latest  

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}  
        script: |
          # Stop and remove any existing container with the name "e-research-container"
          docker stop e-research-container || true
          docker rm e-research-container || true
          
          # Pull the latest image
          docker pull nurhavid1/e-research-server:latest
          
          # Run the new container
          docker run -d -p 8000:8000 --name e-research-container nurhavid1/e-research-server:latest